package ai.deepmost.odyx.config

import android.content.Context
import timber.log.Timber
import java.io.File

/**
 * Loads calibration from assets/ (or the app files dir for user-edited copies).
 * Uses a tiny flat-YAML reader ("key: value", lists as "[a, b, c]") so we avoid
 * pulling in a YAML dependency for these simple files. Falls back to documented
 * defaults (flagged uncalibrated) when a file is missing or unparsable.
 */
object CalibLoader {

    private fun readAssetOrFile(context: Context, name: String): String? {
        // user override in filesDir wins over the bundled asset
        val override = File(context.filesDir, "calib/$name")
        if (override.exists()) return runCatching { override.readText() }.getOrNull()
        return runCatching { context.assets.open("calib/$name").bufferedReader().use { it.readText() } }
            .getOrNull()
    }

    private fun parse(text: String): Map<String, String> {
        val m = HashMap<String, String>()
        text.lineSequence().forEach { raw ->
            val line = raw.substringBefore('#').trim()
            if (line.isEmpty() || !line.contains(':')) return@forEach
            val k = line.substringBefore(':').trim()
            val v = line.substringAfter(':').trim()
            if (k.isNotEmpty()) m[k] = v
        }
        return m
    }

    private fun nums(s: String?): DoubleArray =
        s?.trim('[', ']', ' ')?.split(',', ' ')?.filter { it.isNotBlank() }
            ?.mapNotNull { it.trim().toDoubleOrNull() }?.toDoubleArray() ?: DoubleArray(0)

    fun loadCamera(context: Context): CameraIntrinsics {
        val p = readAssetOrFile(context, "camera_intrinsics.yaml")?.let { parse(it) }
            ?: return CameraIntrinsics()
        val k = nums(p["K"])            // [fx, fy, cx, cy]
        val d = nums(p["distortion"])   // [k1,k2,p1,p2,k3]
        val w = p["width"]?.toIntOrNull() ?: 640
        val h = p["height"]?.toIntOrNull() ?: 480
        if (k.size < 4) return CameraIntrinsics(width = w, height = h)
        val dist = DoubleArray(5) { if (it < d.size) d[it] else 0.0 }
        // A bundled template marks itself `calibrated: false` so the UI keeps the
        // uncalibrated warning until the user supplies a real checkerboard calib.
        val calibrated = p["calibrated"]?.toBooleanStrictOrNull() ?: true
        return CameraIntrinsics(w, h, k[0], k[1], k[2], k[3], dist, valid = calibrated)
    }

    fun loadImu(context: Context): ImuNoise {
        val p = readAssetOrFile(context, "imu_noise.yaml")?.let { parse(it) } ?: return ImuNoise()
        return ImuNoise(
            accN = p["accel_noise_density"]?.toDoubleOrNull() ?: 8.0e-3,
            gyrN = p["gyro_noise_density"]?.toDoubleOrNull() ?: 1.2e-3,
            accW = p["accel_random_walk"]?.toDoubleOrNull() ?: 4.0e-4,
            gyrW = p["gyro_random_walk"]?.toDoubleOrNull() ?: 2.0e-5,
            g = p["gravity"]?.toDoubleOrNull() ?: 9.81
        )
    }

    fun loadExtrinsics(context: Context): Extrinsics {
        val p = readAssetOrFile(context, "cam_imu_extrinsics.yaml")?.let { parse(it) }
            ?: return Extrinsics()
        val q = nums(p["q_bc"])   // [w,x,y,z]
        val t = nums(p["t_bc"])   // [x,y,z]
        val td = p["td"]?.toDoubleOrNull() ?: 0.0
        if (q.size < 4 || t.size < 3) return Extrinsics(td = td)
        val calibrated = p["calibrated"]?.toBooleanStrictOrNull() ?: true
        return Extrinsics(q[0], q[1], q[2], q[3], t[0], t[1], t[2], td, valid = calibrated)
    }

    fun loadLeverArm(context: Context): DoubleArray {
        val p = readAssetOrFile(context, "gnss_lever_arm.yaml")?.let { parse(it) }
            ?: return doubleArrayOf(0.0, 0.0, 0.0)
        val l = nums(p["lever_arm"])
        return if (l.size >= 3) doubleArrayOf(l[0], l[1], l[2]) else doubleArrayOf(0.0, 0.0, 0.0)
    }

    /** Write a calibrated camera_intrinsics.yaml into filesDir/calib (overrides asset). */
    fun writeCameraIntrinsics(context: Context, w: Int, h: Int,
                              fx: Double, fy: Double, cx: Double, cy: Double,
                              dist: DoubleArray, rms: Double) {
        val dir = File(context.filesDir, "calib").apply { mkdirs() }
        File(dir, "camera_intrinsics.yaml").writeText(
            """
            # Generated by ODYX in-app checkerboard calibration (rms=${"%.3f".format(rms)} px).
            calibrated: true
            width: $w
            height: $h
            K: [${"%.4f".format(fx)}, ${"%.4f".format(fy)}, ${"%.4f".format(cx)}, ${"%.4f".format(cy)}]
            distortion: [${dist.joinToString(", ") { "%.6f".format(it) }}]
            """.trimIndent()
        )
    }

    /** Build an OdyxConfig from settings + calibration files. */
    fun buildConfig(context: Context, s: OdyxSettings,
                    cameraReported: CameraIntrinsics? = null): OdyxConfig {
        val loaded = loadCamera(context)
        // Use a real per-device YAML if present; otherwise fall back to the
        // camera-reported intrinsics (much better than the generic default).
        val cam = if (loaded.valid || cameraReported == null) loaded else cameraReported
        val extr = loadExtrinsics(context)
        Timber.tag("Calib").i("camera valid=%s extr valid=%s", cam.valid, extr.valid)
        return OdyxConfig(
            cam = cam, imu = loadImu(context), extr = extr,
            leverArm = loadLeverArm(context),
            targetFeatures = s.targetFeatures, gridCols = s.gridCols, gridRows = s.gridRows,
            kfParallaxPx = s.kfParallaxPx, kfTrackedRatio = s.kfTrackedRatio,
            windowKeyframes = s.windowKeyframes, maxLandmarks = s.maxLandmarks, huberPx = s.huberPx,
            onlineTd = s.onlineTd, onlineExtr = s.onlineExtr, rollingShutter = s.rollingShutter,
            loopEnabled = s.loopEnabled, dbowScoreThresh = s.dbowScoreThresh,
            loopMinInliers = s.loopMinInliers, gnssMode = s.gnssMode, maxKeyframesDb = s.maxKeyframesDb,
            ransacThreshPx = s.ransacThreshPx
        )
    }
}
